# Use Ubuntu 14.04
sudo: required
dist: trusty

# Set the language
language: cpp

# Set the compiler
compiler:
    - gcc

# Sent e-mails if the build fail
notification:
    email:
        on_success: change
        on_failure: always

# Install build packages
install:
    # Check if cmake is installed and, if not, installs it
    - $(which cmake > /dev/null) || (sudo apt-get update && sudo apt-get install cmake) && echo "cmake installed"
    # TODO find a way to get the particle table w/o this environment variable
    - export YAPDIR="$PWD"
    # Get ROOT
    - cd ${TRAVIS_BUILD_DIR}
    - wget https://root.cern.ch/download/root_v6.06.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - mkdir root && tar xf root_v6.06.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz -C root --strip-components 1
    - export ROOTSYS="${TRAVIS_BUILD_DIR}/root"
    - cd ${ROOTSYS} && source $ROOTSYS/bin/thisroot.sh
    # Get BAT
    - cd ${TRAVIS_BUILD_DIR}
    - git clone https://github.com/bat/bat.git
    - cd bat
    - ./autogen.sh
    - ./configure --prefix=`pwd` --with-rootsys=$ROOTSYS --disable-static
    - make -j && make install
    - export BATDIR="${TRAVIS_BUILD_DIR}/bat"
    - export PATH="${BATDIR}/bin:${PATH}"
    - export LD_LIBRARY_PATH="${BATDIR}/lib:${LD_LIBRARY_PATH}"
    # install latest LCOV
    - cd ${TRAVIS_BUILD_DIR}
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
    - tar xf lcov_1.11.orig.tar.gz
    - sudo make -C lcov-1.11/ install
    # install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --zerocounters

# Build
script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --coverage" ..
    - make -j test examples
    - ./test/test
    - ./examples/programs/D3piTest
    - ./examples/programs/D4piTest
    - cd examples/bat_gen && ./runBatGen

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info # capture coverage info
    - lcov --remove coverage.info '/usr/*' 'build/test/catch-prefix/*' 'tools/*' 'include/easylogging++.h' 'root/*' 'bat/*' 'examples/bat_gen/*' --output-file coverage.info # filter out system and catch code
    - lcov --list coverage.info # debug before upload
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
